task1
sogabeharuka/Dojo pull request #1
Opened 2023-06-13 05:13 UTC by sogabeharuka

レビューよろしくお願いします。

2023-06-13 09:06 UTC, natsukiyamada commented on task1/task1.css
> +
ここに追加したcssを記載していただいてもよろしいでしょうか？?
(`.cybozu`, `Kintone`, `Garoon`, `.Office`, `Mailwise`classのcssはこちらに移動しておいてください～)

2023-06-13 09:08 UTC, natsukiyamada commented on task1/task1.css
> +  padding: 2vh 0 2vh 0;
こちら`padding`で上下の余白を指定していますが、
課題の実装条件を見ると「画像には上下左右にマージンを設定する」と記載しているので
marginで上下左右を制御するようにしてください～

2023-06-13 09:15 UTC, natsukiyamada commented on task1/task1.html
> +      </div>
ファイル構成についてですが、画像用のディレクトリを作成して、
その中にpngファイルをいれた方が見やすいですね。対応するかどうかはおまかせします！
以下のようなイメージです。
```
task1
  | - image
  |    | -  Garoon.png
  |    | -  kintone.png
  |    | -  mailwise.png
  |    | -  office.png
  | 
  | - task1.css
  | - task1.html

```

2023-06-13 09:16 UTC, natsukiyamada reviewed
レビューしました！
いくつかコメントしたので確認お願いします～

2023-06-14 07:02 UTC, natsukiyamada commented on task1/task1.css
> +  /* padding: 2vh 0 2vh 0; */
この2行は消していただいてだいじょうぶです！

2023-06-14 07:02 UTC, natsukiyamada requested changes
1点だけ修正お願いします！
https://github.com/sogabeharuka/Dojo/pull/1#discussion_r1229108385

2023-06-15 04:49 UTC, sogabeharuka commented
コメントアウトを削除しました。ご確認よろしくお願い致します。

2023-06-15 05:06 UTC, natsukiyamada approved these changes
内容確認しました！課題完了です~

2023-06-15 05:06 UTC, merged